### ISSUE TITLE
ssh port is not open after emulating firmware using fat.py 

### ISSUE THREAD

**Issue by suruchi1701** [attify/firmware-analysis-toolkit#11] opened 2017-10-26 08:01 UTC
I used to emulate firmware using fat.py, but now ssh port is not open after emulating the same firmware. Earlier it used to work for the same firmware.

Firmware - kkeps.bin

**Comment by adityag** [comment] 2018-01-27 12:10
Can you share the output while emulating the firmware? 
Also run the `reset.sh` and try again.

**Comment by extremecoders-re** [comment] 2018-01-27 12:34
Closing. The issue is probably with upstream firmadyne. 
https://github.com/firmadyne/firmadyne/issues/63

If you need further assistance, feel free to reopen.

**Closed by extremecoders-re** 2018-01-27 12:34 UTC
